# Site settings
title: Mät luftdata själv
short_title: luftdata.se
description: |
    Bygg en egen mätstation för luftpartiklar och bli del
    av ett världsomspännande Citizen Science-nätverk
baseurl: ""
url: "http://luftdata.se"
github_username:  luftdata
github_repo:  luftdata.se
twitter: luftdata
facebook: https://www.facebook.com/groups/luftbubblan
#contact: info@luftdata.se
contact: hannes@ebner.se
luftdaten_map: http://sweden.maps.luftdaten.info

googleanalytics: UA-111883597-1
#google_verification:

contributors:
  -
      name: Hannes Ebner
      link: http://ebner.se
  -
      name: Luftdaten.info
      link: http://luftdaten.info
  -
      name: Sam Smith
      link: http://smth.uk/
  -
      name: Christopher Kullenberg

supporters:
  -
    name: ENTRYSCAPE
    logo: entryscape.png
    footer_logo: entryscape-footer.png
    url: https://entryscape.com
  -
    name: luftdaten.info - OK Lab Stuttgart
    logo: luftdaten.png
    footer_logo: luftdaten-footer.png
    url: http://luftdaten.info

markdown: kramdown

permalink: /:year/:month/:title.html

languages:
  -
    - sv
    - svenska

defaults:
  -
    scope:
      path: "blog"
    values:
      layout: post
      section: blog

related_projects:
  -
      name: luftdaten.info
      link: http://luftdaten.info/
  -
      name: InfluenceAir
      link: http://influencair.be/
  -
      name: Air Bulgaria
      link: https://airbg.info/
  -
      name: openSenseMap
      link: https://opensensemap.org/
